global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - chat_id: 197791750
        parse_mode: 'Markdown'
        bot_token: '6145485605:AAGGrBOmanXJxKEPTSgzLCeh9ERZfeCc3Ms'
