version: '3.7'

services:
  heartbeat:
    build:
      context: extensions/heartbeat/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    command:
      - -e
      - --strict.perms=false
    volumes:
      - ./extensions/heartbeat/config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro,Z
    environment:
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    env_file:
      - /opt/prometheus_stack/docker-elk/.env
    networks:
      - monitoring_network
    depends_on:
      - elasticsearch

