version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - monitoring_network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - monitoring_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress
    networks:
      - monitoring_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - monitoring_network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: "-nginx.scrape-uri=http://nginx_container:80/stub_status"
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - monitoring_network

  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter:latest
    command:
      - --collect.info_schema.tablestats
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=wordpress:wordpress@(db:3306)/
    ports:
      - 9104:9104
    networks:
      - monitoring_network
    links:
      - db
    depends_on:
      - db

volumes:
  db_data: {}

networks:
  monitoring_network:
    external: true

